# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='analysis',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='analysis_comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
