# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0003_journal_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user_id',
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
