# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20170123_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='analysis',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
    ]
