# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anger', models.DecimalField(decimal_places=12, max_digits=13)),
                ('contempt', models.DecimalField(decimal_places=12, max_digits=13)),
                ('disgust', models.DecimalField(decimal_places=12, max_digits=13)),
                ('fear', models.DecimalField(decimal_places=12, max_digits=13)),
                ('happiness', models.DecimalField(decimal_places=12, max_digits=13)),
                ('neutral', models.DecimalField(decimal_places=12, max_digits=13)),
                ('sadness', models.DecimalField(decimal_places=12, max_digits=13)),
                ('suprise', models.DecimalField(decimal_places=12, max_digits=13)),
                ('emotion_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emotion.Emotion')),
            ],
        ),
    ]
