# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expression',
            old_name='suprise',
            new_name='surprise',
        ),
    ]
