# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 23, 52, 37, tzinfo=utc)),
        ),
    ]
