# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='url',
            field=models.ImageField(upload_to='images'),
        ),
    ]
