# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_auto_20170321_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expression',
            old_name='emotion_id',
            new_name='emotion',
        ),
    ]
