# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('topic', models.CharField(choices=[('emotion', 'Emotion'), ('physical', 'Physical Activity'), ('sleep', 'Sleep Activity')], max_length=25)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
