# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('emotion', 'Emotion'), ('physical', 'Physical Activity'), ('sleep', 'Sleep Activity')], default='general', max_length=25),
        ),
    ]
